apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: auth-service
type: Opaque
data:
  # Database credentials (base64 encoded)
  DB_USERNAME: YXV0aF91c2VyX3Byb2Q=  # auth_user_prod
  DB_PASSWORD: eW91ci1zZWN1cmUtcHJvZHVjdGlvbi1wYXNzd29yZA==  # your-secure-production-password
  
  # Redis credentials
  REDIS_PASSWORD: eW91ci1yZWRpcy1wYXNzd29yZA==  # your-redis-password
  
  # JWT secrets (base64 encoded - replace with your own secure secrets)
  JWT_SECRET: eW91ci1zdXBlci1zZWN1cmUtand0LXNlY3JldC01MTItYml0cy1taW5pbXVt  # your-super-secure-jwt-secret-512-bits-minimum
  JWT_REFRESH_SECRET: eW91ci1zdXBlci1zZWN1cmUtcmVmcmVzaC1zZWNyZXQtNTEyLWJpdHMtbWluaW11bQ==  # your-super-secure-refresh-secret-512-bits-minimum
  
  # OAuth credentials (base64 encoded)
  GOOGLE_CLIENT_ID: eW91ci1nb29nbGUtY2xpZW50LWlkLmdvb2dsZXVzZXJjb250ZW50LmNvbQ==  # your-google-client-id.googleusercontent.com
  GOOGLE_CLIENT_SECRET: eW91ci1nb29nbGUtY2xpZW50LXNlY3JldA==  # your-google-client-secret
  
  APPLE_CLIENT_ID: Y29tLnlvdXJjb21wYW55LnlvdXJhcHA=  # com.yourcompany.yourapp
  APPLE_TEAM_ID: eW91ci1hcHBsZS10ZWFtLWlk  # your-apple-team-id
  APPLE_KEY_ID: eW91ci1hcHBsZS1rZXktaWQ=  # your-apple-key-id
  APPLE_PRIVATE_KEY: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCnlvdXItYXBwbGUtcHJpdmF0ZS1rZXkKLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQ==  # your-apple-private-key

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-tls
  namespace: auth-service
type: kubernetes.io/tls
data:
  # TLS certificate and key (base64 encoded)
  # Replace with your actual certificate and key
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t...